### ISSUE TITLE
GotoNextBuildError fails to find file

### ISSUE THREAD

**Issue by kaervin** [slynch8/10x#1090]
Hello, 
GotoNextBuildError fails to find the file of my project.
For a error that is in eg. "main.c(100,10)"  it will try to open "C:/Program Files/PureDevSoftware/10x/main.c" and not the file in the projects directory.
This has worked previously, but broke a few versions ago.

Thanks, 
km.

**Comment by slynch8** [comment]
fixed ().33.30)

**Comment by kaervin** [comment]
Thanks for fixing it, but it still does not work for warnings.

**Comment by slynch8** [comment]
The code is the same for warnings and errors. Could it be that the warning is coming from a different project? If the path is not absolute then I make it relative to the root (sln) workspace.

Can you give an example of what your compiler is outputting?

**Comment by kaervin** [comment]
```
C:\Users\kagami\prog\ngine>call clang-cl -Wpointer-arith -Wpadded -Wpedantic /std:c11 /Od /Z7 /GS /MT main.c /link /SUBSYSTEM:CONSOLE 
main.c(215,9): warning: empty struct is a GNU extension [-Wgnu-empty-struct]
typedef struct SimulationData {
        ^
main.c(694,3): error: use of undeclared identifier 'asdasdasd'
                asdasdasd
                ^
1 warning and 1 error generated.
===== Fail : 2 errors, 1 warnings =====
```
jumps successfully to the error but fails at the warning, same as described above in the issue.

**Comment by slynch8** [comment]
The [ ] was confusing it. Fixed (0.33.32)
