### ISSUE TITLE
typedef with extra decoration incorrectly considers the source type to be the alias.

### ISSUE THREAD

**Issue by zpl-zak** [slynch8/10x#1369]
```c
typedef unsigned __int8 my_u8;
typedef signed __int8 my_i8;
typedef unsigned __int16 my_u16;
typedef signed __int16 my_i16;
typedef unsigned __int32 my_u32;
typedef signed __int32 my_i32;
```

**Actual behavior:**
`__int*` are recognized as types, `my_*` are ignored

**Expected result:**
`my_*` are recognized as types

**Comment by slynch8** [comment]
fixed (0.35.80)

**Comment by zpl-zak** [comment]
Hi, sorry to disturb post-update. It looks like there's one more pair of types that still fails to be parsed properly
```c
    typedef unsigned __int64 my_u64;
    typedef signed __int64 my_i64;
```

That should then cover all the msvc types we typedef.

**Comment by slynch8** [comment]
`__int64` added (0.35.81)
