### ISSUE TITLE
Find Function showing invalid results

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#1403]
Here is an example of the parser going wrong as mentioned in a different issue. This in the Find Function box. You can see SetNextWindowClass is duplicated 7 times in white. Those entries cannot be clicked on.
I had update my imgui.h file earlier in the day.

![10x_imgui](https://user-images.githubusercontent.com/1583441/216238004-0e652860-33da-4e80-8533-d0f631650cc2.png)

**Comment by slynch8** [comment]
I've tried downloading a number of different versions of the file and updating it and I can't get it. Let me know if you can get it again. It would be useful to know which version you updated from/to.

The other thing I wonder is if it's something to do with opening the dialog while a full parse is still in progress.

**Comment by charlesastaylor** [comment]
I have been getting this error also eg:
![image](https://user-images.githubusercontent.com/26279981/225075707-e6605baa-5a41-45bd-a9e1-87fe0a8fb3db.png)

Its happening intermittently, so I can't reproduce it

**Comment by aelthalyste** [comment]
I'm getting this bug too.
![image](https://github.com/slynch8/10x/assets/31110771/197e36d4-7c93-42bf-88be-348c75a00142)
"reparse all" solves the issue but, you know.

It has pretty inconsistent behaviour and I don't have a clue when it occurs. Today, it occured after 30 min of coding, sometimes it happens after hours.

One thing you can try to repro is try to open same file on different panels, one on left one on right. I do this very often and might be causing something but I have literally no idea how 10x handles the situation so it might be off guess.

I don't think it is only limited to duplicate symbols, rather it's overall parser bug. For last few releases -im using the latest 10x on the time being 15.08.2023 version 1.0.69- parser's performance is degraded significantly. Sometimes recently written functions are not parsed, not highlighted etc etc.

**Comment by slynch8** [comment]
Is anyone else using duplicate panels? I just had a repro (that I now can't get again) using a duplicate panel.

**Comment by slynch8** [comment]
I have found some bugs around editing at the end of the file using duplicate panels. These could cause memory corruptions or crashes. Maybe it's stomping the parser memory somehow.

**Comment by Muzza** [comment]
It’s not related to duplicate panels for me. 
Currently I see it more often than ever. If I just edit the file, or edit a files header, I’ll see some syntax highlighting disappear. Then a reparse file is required. 
I can’t reproduce at will, but I’d guess it happens at least once for every 20 minutes of coding.

**Comment by slynch8** [comment]
That's good to know it's not related to duplicate panels.

I have a new theory that it could be related to making changes while a full parse is in progress, or while it's parsing external changes.

Muzza, could I give you a build with asserts enabled to see if it catches anything?

**Comment by slynch8** [comment]
Here's a build with asserts enabled. If anyone wants to give this build a try, unzip and run from that folder.
https://e.pcloud.link/publink/show?code=XZRMbuZTQ8t1QhckQbDK3LmjFtTrH0ai2p7

**Comment by aelthalyste** [comment]
> Here's a build with asserts enabled. If anyone wants to give this build a try, unzip and run from that folder. https://e.pcloud.link/publink/show?code=XZRMbuZTQ8t1QhckQbDK3LmjFtTrH0ai2p7

I'll let you know if something comes out from that tomorrow.

**Comment by slynch8** [comment]
Thanks. I managed to get it again by simple adding whitespace before and after the last function in a file. But annoyingly I lost it while debugging and can't get it again. I think it's something to do with adding/removing large blocks of code.

**Comment by slynch8** [comment]
Got it! I have a fix!!

**Comment by slynch8** [comment]
Finally, this is fixed! (1.0.70) 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Muzza** [comment]
> It’s not related to duplicate panels for me. Currently I see it more often than ever. If I just edit the file, or edit a files header, I’ll see some syntax highlighting disappear. Then a reparse file is required. I can’t reproduce at will, but I’d guess it happens at least once for every 20 minutes of coding.

This has crept back in again some time over the last month or so. I'm finding myself doing a reparse file multiple times an hour.

**Comment by slynch8** [comment]
ok, I'll take a look. Just to confirm, this is just it losing the syntax highlighting for a while rather than the find function panel duplicating results?

**Comment by Muzza** [comment]
Yes the syntax highlighting, go to definition and Find Function all stop working.

**Comment by slynch8** [comment]
The only bug that I have related to this is https://github.com/slynch8/10x/issues/2427 which I investigated today. But it's quite specific, it requires a struct with member functions declared at the start of a function. I'll get it fixed soon, but I doubt it's the cause of your problems.

Can you make sure you have `ColourUndefinedKeywords` set to false, then you can see when things break when they turn white.  Then undo the last few edits and do a ReparseFile, then redo and see if it breaks again.

I really want to get to the bottom of this, but I need a repro. I'll keep on the lookout for any problems here, but aside from the bug above I haven't seen any. Although to be fair I'm not writing a lot of new code at the moment.

**Comment by slynch8** [comment]
Actually, the #2427 bug might be causing other problems. It would happen whenever you have a function inside another function.

Here's a build if you want to give the fix a try:
https://www.10xeditor.com/upload/10xReparseFix2.zip

**Comment by Muzza** [comment]
See gif for a re-producible case
Watch the variable m at the bottom. Doing a reparse file immediately afterwards fixes it.

![SyntaxColourBug](https://github.com/slynch8/10x/assets/1583441/50ec4513-5578-4eab-abca-cf0dc17bd24c)

**Comment by Muzza** [comment]
Another one. See gif

![SyntaxColourBug2](https://github.com/slynch8/10x/assets/1583441/7bbe5fd9-56ac-4baf-b8b0-644bdb9d21f0)

**Comment by slynch8** [comment]
Good find! I'll take a look at these today. Yes, I'm not sure why more people aren't hitting these.

**Comment by slynch8** [comment]
These two reparse issues are now fixed (1.0.156)

**Comment by Muzza** [comment]
Another one:
![SyntaxColourBug3](https://github.com/slynch8/10x/assets/1583441/3c20bb27-3e51-4479-b9db-66ca5fe77c62)

```cpp
#include <vector>
#include <set>

struct A
{
	int foo;
	int bar = 0;
};

extern void Func2( int );

extern void ZAssertMsg( const char* fmt, ... );
extern bool ZAssertFunc( const char* condition, const char* file, int line, const char* function );
#define ASSERT( condition )					if( !(condition) ) { ZAssertMsg( NULL ); ZAssertFunc( #condition, __FILE__, __LINE__, __FUNCTION__ ); } do {} while (false)	// NOTE: while(0) is there to force using a semicolon after Z_ASSERT

void	Func( int startBody, std::set<int>& connectedOut )
{
	bool x = false;

	connectedOut.insert( startBody );
	std::vector<int> todo;
	todo.reserve( 64 );	// insert ASSERT(x); after bool x=false and watch this go white
	todo.push_back( startBody );
}

```

**Comment by Muzza** [comment]
Another one:
![SyntaxColourBug4](https://github.com/slynch8/10x/assets/1583441/1f2a2725-6d63-4912-ae73-1de2924c30a9)

```cpp
struct A
{
	struct Create
	{
		int x;
	};
};

struct V
{
	int x;
	int y;
};

void Func2( void )
{
	V a,b;
	a.x = 0.0f;
	a.y = 0.0f;
	b.x = 0.0f;
	b.y = 0.0f;

	A::Create c;
	c.x = 1; // watch me
}
```

**Comment by slynch8** [comment]
Thanks for the repro's, perfect. I'll get these fixed.

**Comment by Muzza** [comment]
I should mention that there are some cases I've come across where I was unable to create simple reproductions out of what I was seeing in my own code.

**Comment by slynch8** [comment]
I appreciate it's hard to track these down. I've fixed the two above, hopefully they will help other cases as well. I'll upload a new build in a day or two.

**Comment by slynch8** [comment]
These fixes are in (1.0.177). Let me know if you find any more.

**Comment by Muzza** [comment]
I still encounter this happening daily, but don't always get the chance to try and reproduce it. 
This one I did:

![SyntaxColourBug5](https://github.com/user-attachments/assets/595ddee0-816c-41ee-acf3-21f74ec1e735)


```cpp
#include <vector>

struct Vec3i
{
	int x,y,z;
};

void MyFunc( Vec3i a, Vec3i b, std::vector<int>& ary )
{
	Vec3i bmin = a;
	Vec3i bmax = b;
	bmin.x = bmax.x;
}
```

**Comment by slynch8** [comment]
Perfect, good find! It happens for me.

I'll get that fixed.

Make sure you get build (1.0.222), I fixed another reparse bug that you might be hitting.

**Comment by slynch8** [comment]
Fixed in early access build (1.0.224)

**Comment by slynch8** [comment]
This should fix a lot of bugs. It was failing to reparse variables declared with assignment.

**Comment by slynch8** [comment]
I've just uploaded (1.0.227)  which has some more reparse fixes

**Comment by slynch8** [comment]
all the reparse fixes are now in release build (1.0.230)
