### ISSUE TITLE
In a 10x workspace, run command (Ctrl-F5) uses the path specified in "Run working directory" while debug command (F5) doesn't

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#1989]
I have my project set up like this

![image](https://github.com/slynch8/10x/assets/5121492/b1a9e486-faab-4144-8f83-43d939f6f560)

Hitting "run" will execute the run command with the path set to what is specified on "run working directory" but hitting "debug" doesn't use that path, or the one specified in "exe path"

**Comment by slynch8** [comment]
fixed (1.0.70)

**Comment by ggnkua** [comment]
An update for this: the macro $(WorkspaceDirectory) is probably not expanded when hitting the run command, so it still fails

**Comment by slynch8** [comment]
fixed macros (1.0.73)
