### ISSUE TITLE
Bug: Parser doesn't fully handle multiple variables declared in the same statement

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#2319]
If two variables are declared together like this:
![image](https://github.com/slynch8/10x/assets/5231310/b00119ec-30e7-4ed3-9ee8-10fb361c9a5c)

Then only the first variable gets proper syntax highlighting and hover tooltips on its members:
![image](https://github.com/slynch8/10x/assets/5231310/9ec44f89-e049-45e0-9f16-86bcf5da1b6e)

This appears to be because the parser's deduced type for the second variable is wrong.

First variable:
![image](https://github.com/slynch8/10x/assets/5231310/fd026c3b-80da-468d-bc99-21de6323a4cd)

Second variable:
![image](https://github.com/slynch8/10x/assets/5231310/ec5be3f2-970b-4c41-b8d0-74946f0ba1bc)

**Comment by slynch8** [comment]
fixed (1.0.117)

**Comment by dannye** [comment]
I'm still seeing some instances of this type of issue.

For example: https://github.com/dannye/crystal-tracker/blob/9bffd1b/src/piano-roll.cpp#L3285

```cpp
Note_View start_view, end_view;
```

Then when I type `end_view.`, I don't get any autocomplete suggestions.
