### ISSUE TITLE
not releasing memory after closing down

### ISSUE THREAD

**Issue by pixelmager** [slynch8/10x#25]
![image](https://user-images.githubusercontent.com/3230052/104030376-9a11c980-51cb-11eb-8b86-8415aeed28c6.png)
This is after loading the Unreal engine source, and exiting two instances of 10x. Some 5 minutes after.

The processes can be force-closed.

**Comment by slynch8** [comment]
which version is that? I fixed a shutdown hang in (0.20.0.0).

If it still happens in the latest build would you mind forcing a crash dump from TaskManager?

**Comment by pixelmager** [comment]
This is version 20.5.0.

If I just open the solution and shut down, it does not happen. If I search in files first (alt+s), it does hang.

I have a dump-file... but it is of course 11GB.

**Comment by slynch8** [comment]
the dump zips up pretty well, and you can upload it here: [https://www.puredevsoftware.com/upload.htm](https://www.puredevsoftware.com/upload.htm)

but sounds like an easy repro, so let me try first...

**Comment by slynch8** [comment]
I can't reproduce it here, would you mind uploading the dump?

**Comment by pixelmager** [comment]
It's uploaded, 10x.zip, 1.3GB.

**Comment by slynch8** [comment]
thanks, taking a look now

**Comment by slynch8** [comment]
possible fix in (0.20.7.0). In the crash dump it was waiting on msbuild to get the project include paths. I've fixed it so that it won't take as long and will timeout after 30 secs. However, I'm not sure this would have been the cause of the >5 minute shutdown so there may be another problem.

I've also made it automatically generate a crash dump if 10x doesn't shutdown within 2 minutes. This dump will only be a few MB and should show me where it's stuck.

**Comment by pixelmager** [comment]
It still fails to close properly - but did crash after ~2 minutes. 

The pcloud-link no longer works, so I have uploaded the dump to wetransfer: https://we.tl/t-pbEj6OlL99

Thanks!

**Comment by slynch8** [comment]
sorry, I managed to delete the share folder. It's back up again now. Thanks for the dump.

**Comment by slynch8** [comment]
another fix in (0.20.9.0) - think I've got it this time

**Comment by pixelmager** [comment]
confirmed fixed, thanks! (it takes maybe 5 seconds, but then closes as expected)

**Comment by slynch8** [comment]
wohoo! :-)
