### ISSUE TITLE
Perforce integration should try to reconnect if connection has dropped

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#2511]
If the perforce connection has dropped (in 10x) it should auto-reconnect and retry the command. 
For me the connection constantly drops meaning I have to manually run PerforceConnect multiple times a day.

**Comment by slynch8** [comment]
I just tested this and it does appear to reconnect. 
1. I stopped my perforce server
2. I tried checking out a file and it tried to reconnect but failed. 
3. Then I started it up again and tried checking out a different file, and it reconnected successfully and checked out the file.

What's the exact error message that you're getting when it fails?

**Comment by SimpsonGSD** [comment]
all I get in the output log is
```
TCP receive failed.
read: socket: WSAECONNRESET, An existing connection was forcibly closed by
the remote host.
```

**Comment by slynch8** [comment]
Is this in the output panel or log file. And no [perforce]... lines?

**Comment by SimpsonGSD** [comment]
Output panel. No other lines.

**Comment by slynch8** [comment]
Can you check the log file (%appdata%\10x\10x.log), it should show this line
`[perforce] open for edit start`

**Comment by slynch8** [comment]
I've fixed a bug where it wouldn't always try and reconnect if the checkout failed. So maybe this will fix your problem. I plan on uploading a new build tomorrow.

Although it should have logged to the output panel like below, which makes me think something else is going on. Could you have something in a python script that's causing the error message?

![image](https://github.com/slynch8/10x/assets/7141856/d7d2ab2f-98d8-4f41-8f15-6635c8cc16f0)

**Comment by SimpsonGSD** [comment]
It's not just on checkout. Happens for all commands. I don't have anything
in python scripts. This has happened for as long as I can remember but will
have a look at the log file tomorrow.

**Comment by SimpsonGSD** [comment]
Example from log

```
[perforce] open for edit start
[perforce] Failed to open file for edit: <filepath>
Perforce Open for Edit Error <filepath>
TCP send failed.
write: socket: WSAECONNRESET, An existing connection was forcibly closed by the remote host. 
```

**Comment by slynch8** [comment]
Ok, that's good. My change should fix it.

**Comment by SimpsonGSD** [comment]
I'm on Early Access 1.0.137. However the issue still occurs. 
This time it doesn't give me an error and thinks it has succeeded. 
It just kept saying `[perforce] File opened for edit: <filename>`
But it never checked out the file, I had to run `PerforceConnect` and then I could check it out.

**Comment by slynch8** [comment]
I can't remember where we got to with this, is it still an issue?

**Comment by SimpsonGSD** [comment]
I'm monitoring it, I got into a habit of manually running PerforceConnect which hides the problem.

**Comment by SimpsonGSD** [comment]
Yeah still hitting this.

**Comment by KeirMeikle** [comment]
This is trivial to reproduce for me when my auth ticket expires (happens to me every day)

I have 12hr p4 ticket expiry after logging in to p4 via P4V and use PerforceEnableP4Config set to true

Steps to reproduce:
- Log in to p4 in the morning
- Start 10xEditor
- See that it connects fine. i.e I can checkout etc via the 10xeditor UI
- Leave p4v and 10xeditor running for > 12hr. Typically this means I have left my pc on overnight, then return to work next morning
- At this point, p4 has logged me out. P4v asks for password etc.
- Now p4 commands in 10xeditor no longer work (cannot connect, error ui is shown). This is expected.
- Login again to p4 via p4v or command line
- 10xeditor still fails to run p4 commands (same error shown via ui). This is unexpected.

I work around this by restarting 10xeditor after the second p4 login. All p4 commands then start working.
