### ISSUE TITLE
New indent issues

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#49]
This is an old issues that has returned. 10x seems to be basing its indents on the entire file rather than the line I'm on. So in examples like this where I intentionally do not indent after the namespace, every single new line I type results in the wrong indentation. It makes typing very frustrating.

![2021-04-19 14_56_33-Window](https://user-images.githubusercontent.com/1583441/115183637-83aad080-a11f-11eb-951b-c4f535ddf027.png)

**Comment by slynch8** [comment]
I think this is due to the new auto-formatting also indenting lines. Try disabling Parser.AutoFormat and see if that helps. If you do want the formatting but not the indenting I can add another option for that.

**Comment by Muzza** [comment]
I already have that option disabled

**Comment by slynch8** [comment]
Looks like that setting is broken. I'll get that fixed. I can't remember how it worked before with that setting off, do you still want it to indent on a new line after a {, just not on subsequent lines, or do you just never want it to indent?

**Comment by Muzza** [comment]
I want it to indent based upon the code directly above it. 
What it seems to do is set the indentation based on where it would be if it had reformatted the entire file.

**Comment by slynch8** [comment]
This is turning into quite an involved issue. Turns out that the AutoIndent setting didn't actually do anything, so you were using the old indenting system. The indenting now uses the new indenting written for the formatting, but I realise that the indenting as you type has slightly different requirements. Currently trying to fix this to make it work like it did before.

For now I'd recommend going back to a previous version.

**Comment by slynch8** [comment]
I think this is fixed now (0.23.16), it should work as it did before.

Make sure you have the AutoIndent setting _enabled_. The new system will allow you to set the indent to what you want, and everything should then follow from that. It now uses the indentation of the previous statement to work out the current indent.

Let me know if anything doesn't work as expected.

**Comment by Muzza** [comment]
From my brief testing so far it does work in most cases now I think, but the first one I tried failed. See this example:
```
namespace NS1
{

struct Test
{
};	// press return here and the cursor moves 1 tab outwards
```

**Comment by slynch8** [comment]
forgot to try structs. That's fixed now (0.23.20).

Let me know if you find any more cases.

**Comment by Muzza** [comment]
Another issue. It works ok if the #if is at the start of line, but not if it is idented
```
void Test( void )
{
	if( 1 )
	{
		#if SOMETHING	// press return here
	}
}
```

**Comment by Muzza** [comment]
Another example:

```
void Test( void )
{
	if( 1 )	// press return here and...
		// the cursor starts here + moves inwards if you type {

	if( 1 )
		if( 2 )	// press return here and...
		// the cursor starts here
		// and then goes wrong if you type {

	if( 1 )
	if( 2 ) // press return here and it works again

}
```

**Comment by Muzza** [comment]
This one was really bugging me. 10x was incorrectly indenting every line I typed. I eventually found that half a page up, I hadn't yet closed the bracket to a line (the Format call).

```
MyString str;
str.Format( "Intentional error - missing end bracket", xxx

void Func1( void )
{
	// lots of code
}

// everything you type here will go wrong
```

**Comment by Muzza** [comment]
Another example, it's indenting every after macros:

```
// top of file
SOME_MACRO // press return here
```

**Comment by Muzza** [comment]
If you type two } on a single line, it moves the entire line inwards.
I'm not doing it intentionally, but when I accidentally do it, I have to then fix the indentation.

```
	{
	} // type } here
```

**Comment by slynch8** [comment]
New build: 10x (0.24.3).
I've completely re-written the indenting and all of the above should now be fixed, apart from the macro one, which will have to wait for the preprocessor.

This was a big change, so hopefully I haven't broken anything that worked before, let me know if anything goes wrong.

**Comment by Muzza** [comment]
Thanks. I'll continue testing this.
It does seem improved, but I noticed this one still happens:
```
MyString str;
str.Format( "Intentional error - missing end bracket", xxx

void Func1( void )
{
	// lots of code
}

// everything you type here will go wrong
```

Similarly I found that if I have too many end brackets on a line somewhere above the current point. The ident will go straight to the left hand side from then on.

**Comment by Muzza** [comment]
Enums aren't indenting correctly:
```
enum MYENUM
{
	MYENUM_A,	// press return here
```

**Comment by slynch8** [comment]
I've fixed enums (0.24.5).

I checked the "missing end bracket" bug and it is working for me if I type in Func1 or after Func1. Typing before the Func1 brace will indent but that is expected because the statement isn't terminated. Any statement that isn't terminated will be indented on the next line, examples:

**Comment by slynch8** [comment]
I'm not sure I can fix the double close brace. If you close a brace then it will take the current indent from the matching open brace which is almost always what you want. I'm not sure how I could detect that it had happened accidently. But I'm open to suggestions.

**Comment by Muzza** [comment]
Example below. This one only seems to go wrong when public/protected/private is above the struct.

```
struct A
{
public:
	struct B	// press return then { here

};
```
