### ISSUE TITLE
Parser issue after #define

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#61]
If I place this function after the macro, the parser leaves various symbols white.
![2021-05-22 13_17_13-Window](https://user-images.githubusercontent.com/1583441/119213098-3051e680-bb00-11eb-8ea4-7bee125c17cc.png)

If I place it before the macro, it recognises them (mIncludes remains white - but that is correct as it was a typo)
![2021-05-22 13_17_35-Window](https://user-images.githubusercontent.com/1583441/119213104-3647c780-bb00-11eb-9034-755cbe5c9d92.png)

Other member functions after this point are all fine, so I don't know why this particular function is doing this.

**Comment by Muzza** [comment]
The parsing was getting screwy all over in that file, I deleted the 10x_parser_cache file and reopened the project, and it seems to have corrected itself. There is definitely something that breaks the parser with regular editing. I've had a few cases where deleting the cache fixes things.

**Comment by slynch8** [comment]
I've tried that in a test file and couldn't get it to happen. I'll try and find a repro. Let me know if you spot any pattern to when it breaks.

**Comment by slynch8** [comment]
I've found a problem with multiple 'using namespace', looks like it might be the cause, did that function immediately follow a using namespace?

eg, this would fail:
```
using namespace Namespace1;
using namespace Namespace2;

MyClassInNamespace2::MyClassInNamespace2() <-- fail
{
}
```

**Comment by slynch8** [comment]
Hopefully that's it, fixed in (0.25.7)

**Comment by Muzza** [comment]
The entire class was inside a namespace, but there were no 'using namespace' in the file.
My feeling is that it probably was nothing particular to this piece of code, more that there is some rare bug that crops up with heavy editing. Its not the first time I've had a file do this, and deleting the cache fixes it.

**Comment by Muzza** [comment]
Same file after a bit of editing. The search window is showing the last function four times, three of them in white. It only exists once.

![2021-05-23 16_59_47-Window](https://user-images.githubusercontent.com/1583441/119251161-64a0d200-bbe8-11eb-82e0-6ec27da14b84.png)

**Comment by slynch8** [comment]
The bug might have affected more than just using statements. Is it still happening after updating?

I'm sure you're right that it's just general editing, but would it be possible to share the file anyway, it might help me to reproduce it.

**Comment by Muzza** [comment]
Well it went away after deleting the parser cache so I don't know if the update had an effect, but as you can see, errors start to creep back in as I work on the file

**Comment by slynch8** [comment]
So those errors in the search window are since updating?

**Comment by Muzza** [comment]
Yes

**Comment by Muzza** [comment]
Another example of the same file getting messed up:
![2021-05-24 08_39_54-Window](https://user-images.githubusercontent.com/1583441/119278910-bf2f4200-bc6b-11eb-9230-f88507d99d19.png)

Somehow 10x has interpreted the /* within the quotes as the start of a real comment, and everything after it shows in green. I can't reproduce this in a test file, and as soon as I deleted and re-added the quotes it fixed itself.
I hadn't touched this line of code or anything near to it in days.

**Comment by slynch8** [comment]
As you say, it doesn't repro in a simple test. I wonder if there is something different about your setup. Remind me, are you using a sln, 10x_workspace or folder workspace, and do you have any Additional Include paths setup?

**Comment by slynch8** [comment]
I think I've found the cause of the original bug, and possibly the /* bug as well. Fix in (0.25.8).

When typing a line sometimes it wasn't updating the next line.

**Comment by Muzza** [comment]
Sorry, I missed replying to this, but I'm using a sln with no include paths.

It continues to get corrupted. Find Function for 'Def' brings up to function at line zero, that do not have Def in them.
![2021-05-26 16_47_18-Window](https://user-images.githubusercontent.com/1583441/119614885-269eea80-be42-11eb-9d15-a66b71d7af8a.png)

When I search the Pop, the real function appears, but not the two bad results.
![2021-05-26 16_47_36-Window](https://user-images.githubusercontent.com/1583441/119614891-27d01780-be42-11eb-8bf8-9af8e8ddddc6.png)

**Comment by slynch8** [comment]
If you spot a repro for this I'm happy to investigate, but otherwise I can't think of anything to suggest. I just can't get it to happen.

I'm currently working on the preprocessor, so maybe I'll spot something along the way.

One theory I had is that it's due to editing while it's doing the initial parse. Try deleting your cache, then wait until the parse has finished (and finished writing, see the output panel) before editing.

**Comment by Muzza** [comment]
Just had a thought about this.
Whenever I'm doing a bug report, I open 10x twice. Once with my main project and once with a simple test project for trying to reproduce the error.
When I open the second instance, 10x automatically loads the same sln that I already have open. I never edit this second instance, I just switch to the test folder straight away.
In the past 10x would often crash if I loaded the same sln twice. It no longer crashes but I always worry a little about how it is handling the cache files in this situation. Could it be corrupting them? Perhaps 10x should detect already open workspaces and not try to open them twice.

**Comment by slynch8** [comment]
That's an interesting theory. I can't think of any reason why it would cause a problem, the cache just just read once on open and written on close, the file is locked by each process. But I haven't given it a lot of testing so you could be right that there is a bug here. Something that might have bugs though is closing a workspace and opening another one, there might be some global state lying around that isn't being cleared. I'll see what I can find.

**Comment by slynch8** [comment]
I've found that editing a file while the initial parse is happening can break the parser, for that file and possibly other files. I'm investigating. But for now probably best to wait for the parser to complete.

**Comment by slynch8** [comment]
This is fixed now (0.25.16). I'm really hoping this was the cause of the random parser failures. Let me know if you see anything similar in this build.

**Comment by Muzza** [comment]
I'm still getting problems I'm afraid. For example, after a bit of editing today, one file (a different one than before) is showing bad entries in the Find Function list (duplicated functions showing in white at line zero).
I set up a keyboard shortcut that closes the workspace, deletes all cache files, then reopens the workspace. I run this a couple of times a day to avoid the parser errors getting out of hand.

**Comment by slynch8** [comment]
Is it just Find Function that is affected, or are you still getting problems with syntax highlighting and goto-def?

**Comment by Muzza** [comment]
I only noticed Find Function, and I deleted my cache afterwards. I'll keep looking for other issues next time.

**Comment by Muzza** [comment]
To follow up on this, I've had fewer problems with syntax highlighting and goto-def, but I still get Find Function giving invalid results at line 0 quite regularly after editing a file for a while.

**Comment by slynch8** [comment]
Closing. Will now track the function list bug here: https://github.com/slynch8/10x/issues/303
