### ISSUE TITLE
Windows 11 Rendering Issues

### ISSUE THREAD

**Issue by ForestCSharp** [slynch8/10x#745]
I'm seeing a semi-transparent border around the 10x window on Windows 11. There also seems to be some other rendering issues (notably the config dropdown, as seen in the attached image).

![image](https://user-images.githubusercontent.com/7401287/153331777-851b7981-c0b3-44bb-be67-57f8502e4abc.png)

**Comment by ForestCSharp** [comment]
I was using 10x on another (Windows 10) machine so I suspect this is related to Windows 11?

**Comment by slynch8** [comment]
Are you on the latest version? I thought I fixed that last week.

**Comment by ForestCSharp** [comment]
I had just downloaded it from the website last night.

**Comment by ForestCSharp** [comment]
I just tried deleting that folder. Still seeing the issue, unfortunately.

**Comment by slynch8** [comment]
ok, a few questions:
1. does resizing the window fix it?
2. does maximising fix it?
3. What version of Win11 are you on?

Other users on Win11 aren't seeing this anymore, so I wonder if it's been fixed in a more recent Win11 version

**Comment by slynch8** [comment]
ok, thanks for checking. It's difficult for me to test this as my PC can't run Win11, but I'll see if there is anything I can try. 

It's odd that it's fine for some people and not others. I wonder if it is related to a different windows setting, maybe a transparent Windows background colour.

**Comment by Dolichomps** [comment]
I also have the exact same issue, I have 2 pcs with windows 11. Only one has the issue, the one with the issue is a laptop with an integrated intel gpu. The one without the issue is a desktop with a dedicated amd gpu. Windows version is 21H2 build 22000.593 intel gpudriver version is 30.0.101.1660. 10x was installed today as well as windows so everything is fresh. I have tried toggling transparency effects but it doesn't change. Very strange.

**Comment by evzen-muller** [comment]
I see the same issue with 0.32.13 on Windows 11 Pro, 21H2, 22000.675. with Intel (Iris XE) GPU. It shows all the time, even when dragging or resizing the window.

**Comment by slynch8** [comment]
If this is still happening for anyone would you be prepared to try a few things for me?

**Comment by slynch8** [comment]
possible fix in (0.32.18). Let me know if you're still getting it, there are a f ew more things I can try.

**Comment by slynch8** [comment]
potential fix, can someone try this build: https://t.co/l92cThvahy

**Comment by slynch8** [comment]
fixed (0.34.19)
