### ISSUE TITLE
Delay on opening 10x

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#80]
In one of the recent builds, the time taken to start 10x has increased significantly. It used to be almost instant from opening the program to be able to scroll through files, but currently it freezes for 6 or 7 seconds with the display inactive.
The pause happens even after clearing the parser cache.

```
[python] Executing script UE4CompileSingleFile 0ms
  < pause occurs here >
[parser] Parsing files (5905)...
[parser] Read cache complete
[parser] Read cache time: 1433 ms
[parser] Finished reading workspace files
[parser] Finished parsing
[parser] Updating syntax highlighting...
[parser] Finished updating syntax highlighting
[parser] Parse complete
[parser] total parse time: 6759 ms
[parser] Parse complete
```

**Comment by slynch8** [comment]
I'm not getting this. Could it be one of your python scripts?

**Comment by slynch8** [comment]
Fixed (0.26.15)

**Comment by Muzza** [comment]
Still happening 0.26.16 unfortunately.
I've tried to capture a dump file at the right place.
[Dump file here.](https://www.dropbox.com/s/gz96u2qhog8rg7x/10xDump.zip?dl=0)

**Comment by slynch8** [comment]
I think I see what's happening. There is a variable in a vsxproj file that can't be resolved, so it's trying to resolve it each time it sees it. I'm now caching it even if it can't resolve, hopefully that fixes it (0.26.17)

**Comment by Muzza** [comment]
Much better, it's less than 2 seconds now.
