### ISSUE TITLE
include paths bug

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#813]
Here is an approximation of the project set up:

Project A files:
EASTL/Map.h
HeaderA.h <-- does include <EASTL/Map.h>

Project B files:
Map.h
HeaderB.h <-- does include "HeaderA.h", include "Map.h"

If I do 'Go to definition' on the #include "Map.h" in HeaderB.h, 10x takes map to EASTL/Map.h instead of the one in the local project.
Similarly, no macros defines in ProjectB's Map.h show up properly, but if I put the macros in EASTL/Map.h, they do.

Hard to say for sure what is happening, because in reality the project setup is more complicated than this, but it feels as though 10x is not handling include paths correctly when there are duplicate filenames across different projects.

**Comment by slynch8** [comment]
I couldn't repro this, but I think I've found the problem
fixed (0.31.41)

**Comment by Muzza** [comment]
This has fixed the 'Go to definition' function opening the wrong file. But it has not fixed the pre-processor, so I guess this was two different problems. It may be to do with the Force Includes project setting instead.

Project B:
Map.h
HeaderB.h <-- does Include "Map.h" as well as many other files

Project C:
Does a force include of "HeaderB.h" in the project settings

When looking at .c files in ProjectB, the preprocessor seems to be working correctly even for macros in Map.h.
When looking at .c files in ProjectC, anything in Map.h is missing, but other files seem to be working, and if I move the macros from Map.h to another file in ProjectB, the preprocessor finds them. So it feels as though Map.h specifically is being ignored.
